"""Initial migration

Revision ID: f8ace9e0f86e
Revises: 
Create Date: 2025-12-29 19:06:47.766150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ace9e0f86e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('weight_unit_preference', sa.Enum('LBS', 'KG', name='weightunit'), nullable=False),
    sa.Column('rounding_increment', sa.Float(), nullable=False),
    sa.Column('missed_workout_preference', sa.Enum('SKIP', 'RESCHEDULE', 'ASK', name='missedworkoutpreference'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('PUSH', 'PULL', 'LEGS', 'CORE', name='exercisecategory'), nullable=False),
    sa.Column('is_predefined', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_user_id'), 'exercises', ['user_id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('target_cycles', sa.Integer(), nullable=True),
    sa.Column('training_days', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', name='programstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_user_id'), 'programs', ['user_id'], unique=False)
    op.create_table('warmup_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lift_type', sa.Enum('SQUAT', 'DEADLIFT', 'BENCH_PRESS', 'PRESS', name='lifttype'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sets', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warmup_templates_user_id'), 'warmup_templates', ['user_id'], unique=False)
    op.create_table('program_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('main_lift', sa.Enum('SQUAT', 'DEADLIFT', 'BENCH_PRESS', 'PRESS', name='lifttype'), nullable=False),
    sa.Column('accessories', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_templates_program_id'), 'program_templates', ['program_id'], unique=False)
    op.create_table('training_max_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('lift_type', sa.Enum('SQUAT', 'DEADLIFT', 'BENCH_PRESS', 'PRESS', name='lifttype'), nullable=False),
    sa.Column('old_value', sa.Float(), nullable=True),
    sa.Column('new_value', sa.Float(), nullable=False),
    sa.Column('change_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Enum('INITIAL', 'CYCLE_COMPLETION', 'DELOAD', 'FAILED_REPS', 'MANUAL', name='trainingmaxreason'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_max_history_program_id'), 'training_max_history', ['program_id'], unique=False)
    op.create_table('training_maxes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('lift_type', sa.Enum('SQUAT', 'DEADLIFT', 'BENCH_PRESS', 'PRESS', name='lifttype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('INITIAL', 'CYCLE_COMPLETION', 'DELOAD', 'FAILED_REPS', 'MANUAL', name='trainingmaxreason'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_maxes_program_id'), 'training_maxes', ['program_id'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_type', sa.Enum('WEEK_1_5S', 'WEEK_2_3S', 'WEEK_3_531', 'WEEK_4_DELOAD', name='weektype'), nullable=False),
    sa.Column('main_lift', sa.Enum('SQUAT', 'DEADLIFT', 'BENCH_PRESS', 'PRESS', name='lifttype'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', name='workoutstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_program_id'), 'workouts', ['program_id'], unique=False)
    op.create_index(op.f('ix_workouts_scheduled_date'), 'workouts', ['scheduled_date'], unique=False)
    op.create_table('workout_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workout_id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('set_type', sa.Enum('WARMUP', 'WORKING', 'ACCESSORY', 'AMRAP', name='settype'), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('prescribed_reps', sa.Integer(), nullable=True),
    sa.Column('actual_reps', sa.Integer(), nullable=False),
    sa.Column('prescribed_weight', sa.Float(), nullable=True),
    sa.Column('actual_weight', sa.Float(), nullable=False),
    sa.Column('weight_unit', sa.Enum('LBS', 'KG', name='weightunit'), nullable=False),
    sa.Column('percentage_of_tm', sa.Float(), nullable=True),
    sa.Column('is_target_met', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sets_workout_id'), 'workout_sets', ['workout_id'], unique=False)
    op.create_table('rep_maxes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lift_type', sa.Enum('SQUAT', 'DEADLIFT', 'BENCH_PRESS', 'PRESS', name='lifttype'), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('weight_unit', sa.Enum('LBS', 'KG', name='weightunit'), nullable=False),
    sa.Column('calculated_1rm', sa.Float(), nullable=False),
    sa.Column('achieved_date', sa.Date(), nullable=False),
    sa.Column('workout_set_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_set_id'], ['workout_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rep_maxes_lift_type'), 'rep_maxes', ['lift_type'], unique=False)
    op.create_index(op.f('ix_rep_maxes_user_id'), 'rep_maxes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rep_maxes_user_id'), table_name='rep_maxes')
    op.drop_index(op.f('ix_rep_maxes_lift_type'), table_name='rep_maxes')
    op.drop_table('rep_maxes')
    op.drop_index(op.f('ix_workout_sets_workout_id'), table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_index(op.f('ix_workouts_scheduled_date'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_program_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_training_maxes_program_id'), table_name='training_maxes')
    op.drop_table('training_maxes')
    op.drop_index(op.f('ix_training_max_history_program_id'), table_name='training_max_history')
    op.drop_table('training_max_history')
    op.drop_index(op.f('ix_program_templates_program_id'), table_name='program_templates')
    op.drop_table('program_templates')
    op.drop_index(op.f('ix_warmup_templates_user_id'), table_name='warmup_templates')
    op.drop_table('warmup_templates')
    op.drop_index(op.f('ix_programs_user_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_exercises_user_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
